#!/usr/bin/env bash
set -euo pipefail

AUDIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$AUDIT_DIR/toolchain.lock"

AUDIT_TOOL_BASE="${RUNNER_TEMP:-/tmp}/gumball6900-audit-tools"
AUDIT_BIN_DIR="$AUDIT_TOOL_BASE/bin"
AUDIT_PIPX_HOME="$AUDIT_TOOL_BASE/pipx"
AUDIT_BOOTSTRAP_VENV="$AUDIT_TOOL_BASE/bootstrap"
INSTALL_PROFILE="${1:-nightly}"

if [[ "$INSTALL_PROFILE" != "static" && "$INSTALL_PROFILE" != "nightly" ]]; then
    echo "Usage: $0 [static|nightly]" >&2
    exit 1
fi

verify_sha256() {
    local expected="$1"
    local archive="$2"

    if command -v sha256sum >/dev/null 2>&1; then
        [[ "$(sha256sum "$archive" | awk '{print $1}')" == "$expected" ]]
        return
    fi
    if command -v shasum >/dev/null 2>&1; then
        [[ "$(shasum -a 256 "$archive" | awk '{print $1}')" == "$expected" ]]
        return
    fi

    echo "No SHA-256 verification utility is available." >&2
    return 1
}

install_hash_locked_analyzer() {
    local analyzer="$1"
    local executable="$2"
    local lock_path="$AUDIT_DIR/python-locks/$analyzer-linux-x64.txt"
    local virtualenv="$AUDIT_TOOL_BASE/$analyzer"
    local expected_sha256

    case "$analyzer" in
        semgrep) expected_sha256="$ANALYZER_SEMGREP_LOCK_SHA256" ;;
        slither) expected_sha256="$ANALYZER_SLITHER_LOCK_SHA256" ;;
        *)
            echo "Unknown hash-locked analyzer: $analyzer" >&2
            exit 1
            ;;
    esac
    verify_sha256 "$expected_sha256" "$lock_path"

    python3 -m venv --clear "$virtualenv"
    "$virtualenv/bin/python" -I -m pip --isolated \
        --disable-pip-version-check \
        --no-input \
        install \
        --only-binary=:all: \
        --require-hashes \
        --requirement "$lock_path"
    "$virtualenv/bin/python" -I -m pip --isolated --disable-pip-version-check check
    if [[ ! -x "$virtualenv/bin/$executable" ]]; then
        echo "Hash-locked $analyzer environment did not install $executable." >&2
        exit 1
    fi
    ln -sf "$virtualenv/bin/$executable" "$AUDIT_BIN_DIR/$executable"
}

mkdir -p "$AUDIT_BIN_DIR"
ANALYZER_ENVIRONMENT_FILE="$AUDIT_TOOL_BASE/analyzer-environment.env"
if [[ "$(uname -s):$(uname -m)" == Linux:x86_64 ]]; then
    node "$AUDIT_DIR/resolve-analyzer-environment.mjs" \
        --workspace "$(cd "$AUDIT_DIR/../../.." && pwd)" \
        --shell-output "$ANALYZER_ENVIRONMENT_FILE" \
        --verify-python python3
else
    node "$AUDIT_DIR/resolve-analyzer-environment.mjs" \
        --workspace "$(cd "$AUDIT_DIR/../../.." && pwd)" \
        --shell-output "$ANALYZER_ENVIRONMENT_FILE"
fi
# This file is generated by the resolver from enum and exact-version values only.
source "$ANALYZER_ENVIRONMENT_FILE"
ANALYZER_DEPENDENCIES_PREPARED=false
if [[ "$ANALYZER_INSTALLATION_MODE" == hash-locked-requirements-and-container ]]; then
    ANALYZER_DEPENDENCIES_PREPARED=true
fi
if [[ "$(uname -s):$(uname -m)" == Darwin:arm64 && "$ANALYZER_DEPENDENCIES_PREPARED" == true ]]; then
    ANALYZER_ENVIRONMENT_STATE=local-darwin-engineering-fallback
    ANALYZER_INSTALLATION_MODE=top-level-pipx-engineering
fi

case "$ANALYZER_ENVIRONMENT_STATE:$ANALYZER_INSTALLATION_MODE" in
    configured:hash-locked-requirements-and-container | dependencies-prepared:hash-locked-requirements-and-container)
        install_hash_locked_analyzer slither slither
        install_hash_locked_analyzer semgrep semgrep
        ;;
    transitive-dependencies-unlocked:top-level-pipx-engineering | local-darwin-engineering-fallback:top-level-pipx-engineering)
        python3 -m venv --clear "$AUDIT_BOOTSTRAP_VENV"
        "$AUDIT_BOOTSTRAP_VENV/bin/python" -m pip install --disable-pip-version-check "pipx==$PIPX_VERSION"
        export PIPX_BIN_DIR="$AUDIT_BIN_DIR"
        export PIPX_HOME="$AUDIT_PIPX_HOME"
        "$AUDIT_BOOTSTRAP_VENV/bin/pipx" install --force "slither-analyzer==$SLITHER_VERSION"
        "$AUDIT_BOOTSTRAP_VENV/bin/pipx" install --force "semgrep==$SEMGREP_VERSION"
        ;;
    *)
        echo "Unsupported analyzer environment resolution." >&2
        exit 1
        ;;
esac

case "$(uname -s):$(uname -m)" in
    Linux:x86_64)
        ADERYN_TARGET="x86_64-unknown-linux-gnu"
        ADERYN_SHA256="$ADERYN_LINUX_X86_64_SHA256"
        GITLEAKS_TARGET="linux_x64"
        GITLEAKS_SHA256="$GITLEAKS_LINUX_X86_64_SHA256"
        ;;
    Darwin:arm64)
        ADERYN_TARGET="aarch64-apple-darwin"
        ADERYN_SHA256="$ADERYN_DARWIN_ARM64_SHA256"
        GITLEAKS_TARGET="darwin_arm64"
        GITLEAKS_SHA256="$GITLEAKS_DARWIN_ARM64_SHA256"
        ;;
    *)
        echo "Pinned Aderyn and Gitleaks installation supports Linux x86_64 and Darwin arm64 only." >&2
        exit 1
        ;;
esac

ADERYN_ARCHIVE="$AUDIT_TOOL_BASE/aderyn-$ADERYN_TARGET.tar.xz"
ADERYN_EXTRACT_DIR="$AUDIT_TOOL_BASE/aderyn-$ADERYN_VERSION"
curl --fail --location --silent --show-error \
    "https://github.com/Cyfrin/aderyn/releases/download/aderyn-v$ADERYN_VERSION/aderyn-$ADERYN_TARGET.tar.xz" \
    --output "$ADERYN_ARCHIVE"
verify_sha256 "$ADERYN_SHA256" "$ADERYN_ARCHIVE"
mkdir -p "$ADERYN_EXTRACT_DIR"
tar --extract --xz --file "$ADERYN_ARCHIVE" --directory "$ADERYN_EXTRACT_DIR"
install -m 0755 \
    "$ADERYN_EXTRACT_DIR/aderyn-$ADERYN_TARGET/aderyn" \
    "$AUDIT_BIN_DIR/aderyn"

GITLEAKS_ARCHIVE="$AUDIT_TOOL_BASE/gitleaks-$GITLEAKS_TARGET.tar.gz"
curl --fail --location --silent --show-error \
    "https://github.com/gitleaks/gitleaks/releases/download/v$GITLEAKS_VERSION/gitleaks_${GITLEAKS_VERSION}_$GITLEAKS_TARGET.tar.gz" \
    --output "$GITLEAKS_ARCHIVE"
verify_sha256 "$GITLEAKS_SHA256" "$GITLEAKS_ARCHIVE"
tar --extract --gzip --file "$GITLEAKS_ARCHIVE" --directory "$AUDIT_BIN_DIR" gitleaks
chmod 0755 "$AUDIT_BIN_DIR/gitleaks"

if [[ "$INSTALL_PROFILE" == "nightly" ]]; then
    if [[ "$ANALYZER_DEPENDENCIES_PREPARED" == true ]]; then
        MYTHRIL_IMAGE="mythril/myth:$MYTHRIL_VERSION@$MYTHRIL_IMAGE_DIGEST"
        if [[ "$ANALYZER_MYTHRIL_IMAGE" != "$MYTHRIL_IMAGE" ]]; then
            echo "Analyzer policy and toolchain lock disagree on the Mythril image." >&2
            exit 1
        fi
        docker pull --platform linux/amd64 "$MYTHRIL_IMAGE"
        printf '%s\n' \
            '#!/usr/bin/env bash' \
            'set -euo pipefail' \
            "exec docker run --rm --platform linux/amd64 --pull=never \"$MYTHRIL_IMAGE\" \"\$@\"" \
            >"$AUDIT_BIN_DIR/myth"
        chmod 0755 "$AUDIT_BIN_DIR/myth"
    else
        "$AUDIT_BOOTSTRAP_VENV/bin/pipx" install --force "mythril==$MYTHRIL_VERSION"
    fi
    GOBIN="$AUDIT_BIN_DIR" go install "github.com/crytic/medusa@v$MEDUSA_VERSION"
    ECHIDNA_IMAGE="ghcr.io/crytic/echidna/echidna:v$ECHIDNA_VERSION@$ECHIDNA_IMAGE_DIGEST"
    docker pull --platform linux/amd64 "$ECHIDNA_IMAGE"
fi

if [[ -n "${GITHUB_PATH:-}" ]]; then
    printf '%s\n' "$AUDIT_BIN_DIR" >> "$GITHUB_PATH"
fi

export PATH="$AUDIT_BIN_DIR:$PATH"
slither --version
aderyn --version
semgrep --version
gitleaks version
if [[ "$INSTALL_PROFILE" == "nightly" ]]; then
    medusa --version
    myth version
    docker image inspect "$ECHIDNA_IMAGE" --format '{{json .RepoDigests}}'
fi
