#!/usr/bin/env node

import { execFile } from 'node:child_process';
import { cp, mkdtemp, mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, dirname, relative, resolve } from 'node:path';
import { promisify } from 'node:util';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const executeFile = promisify(execFile);
const require = createRequire(import.meta.url);
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageDirectory = resolve(scriptDirectory, '..');
const repositoryDirectory = resolve(packageDirectory, '../..');
const outputDirectory = resolve(repositoryDirectory, 'docs/reference/sdk');
const optionsPath = resolve(packageDirectory, 'typedoc.json');
const typedocPackageDirectory = dirname(require.resolve('typedoc/package.json'));
const typedocBinary = resolve(typedocPackageDirectory, 'bin/typedoc');
const checkOnly = process.argv.includes('--check');

function compareCodeUnits(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

async function filesBelow(directory, prefix = '') {
  const entries = await readdir(directory, { withFileTypes: true }).catch((error) => {
    if (error.code === 'ENOENT') return [];
    throw error;
  });
  const files = [];
  for (const entry of entries.sort((left, right) => compareCodeUnits(left.name, right.name))) {
    const path = resolve(directory, entry.name);
    const name = prefix === '' ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) files.push(...(await filesBelow(path, name)));
    else if (entry.isFile()) files.push(name);
  }
  return files;
}

async function generateInto(directory) {
  try {
    const { stderr, stdout } = await executeFile(
      process.execPath,
      [typedocBinary, '--options', optionsPath, '--out', directory],
      { cwd: packageDirectory, maxBuffer: 64 * 1024 * 1024 },
    );
    if (stdout.trim() !== '') process.stdout.write(stdout);
    if (stderr.trim() !== '') process.stderr.write(stderr);
  } catch (error) {
    if (typeof error.stdout === 'string' && error.stdout !== '') process.stdout.write(error.stdout);
    if (typeof error.stderr === 'string' && error.stderr !== '') process.stderr.write(error.stderr);
    throw new Error(`TypeDoc generation failed with exit code ${String(error.code ?? 'unknown')}.`, { cause: error });
  }

  const readmePath = resolve(directory, 'README.md');
  const readme = await readFile(readmePath, 'utf8');
  const banner =
    '<!-- Generated by packages/sdk/scripts/generate-docs.mjs from the public SDK entry point. Do not edit. -->\n\n';
  await writeFile(readmePath, `${banner}${readme}`);
}

async function compareDirectories(expectedDirectory, actualDirectory) {
  const expectedFiles = await filesBelow(expectedDirectory);
  const actualFiles = await filesBelow(actualDirectory);
  const expectedNames = new Set(expectedFiles);
  const actualNames = new Set(actualFiles);
  const differences = [];

  for (const path of expectedFiles) {
    if (!actualNames.has(path)) {
      differences.push(`missing ${path}`);
      continue;
    }
    const [expected, actual] = await Promise.all([
      readFile(resolve(expectedDirectory, path)),
      readFile(resolve(actualDirectory, path)),
    ]);
    if (!expected.equals(actual)) differences.push(`changed ${path}`);
  }
  for (const path of actualFiles) if (!expectedNames.has(path)) differences.push(`unexpected ${path}`);

  return differences.sort(compareCodeUnits);
}

async function replaceGeneratedDirectory(generatedDirectory) {
  await mkdir(dirname(outputDirectory), { recursive: true });
  await rm(outputDirectory, { force: true, recursive: true });
  try {
    await rename(generatedDirectory, outputDirectory);
  } catch (error) {
    if (error.code !== 'EXDEV') throw error;
    await cp(generatedDirectory, outputDirectory, { recursive: true });
  }
}

const temporaryRoot = await mkdtemp(resolve(tmpdir(), 'gumball-6900-sdk-docs-'));
const generatedDirectory = resolve(temporaryRoot, 'sdk');
try {
  await generateInto(generatedDirectory);
  if (checkOnly) {
    const differences = await compareDirectories(generatedDirectory, outputDirectory);
    if (differences.length > 0) {
      const preview = differences.slice(0, 20).map((difference) => `  - ${difference}`);
      if (differences.length > preview.length) preview.push(`  - and ${differences.length - preview.length} more`);
      console.error(['Generated SDK API reference is stale. Run `pnpm docs:generate`.', ...preview].join('\n'));
      process.exitCode = 1;
    }
  } else {
    await replaceGeneratedDirectory(generatedDirectory);
    console.log(
      `Generated ${basename(outputDirectory)} API reference at ${relative(repositoryDirectory, outputDirectory)}.`,
    );
  }
} finally {
  await rm(temporaryRoot, { force: true, recursive: true });
}
