name: Main branch

on:
  push:
    branches: [main]

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  baseline:
    uses: ./.github/workflows/pr.yml
    permissions:
      contents: read
      security-events: write
